spring:
  profiles:
    active: prod
server:
  port: 8080

  datasource:
    #1.数据库连接
    #连接名 如果存在多个连接 可以用此名称区分
    name: mysql
    url: jdbc:mysql://localhost:3306/struggle?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    #2.数据源配置 指定Druid数据源 Spring Boot 2.0 以上默认使用 com.zaxxer.hikari.HikariDataSource 数据源
    type: com.alibaba.druid.pool.DruidDataSource
    #配置监控统计拦截的filters。stat:监控统计、log4j：日志记录、wall：防御sql注入
    filters: stat,log4j,wall
    # 最大连接池数量
    maxActive: 20
    # 初始化时建立物理连接的个数
    initialSize: 1
    # 获取连接时最大等待时间，单位毫秒。
    maxWait: 6000
    # 最小连接池数量
    minIdle: 1
    # 1.Destroy线程会检测连接的间隔时间 2.testWhileIdle的判断依据
    timeBetweenEvictionRunsMillis: 60000
    # 连接保持空闲⽽而不不被驱逐的最⻓长时间
    minEvictableIdleTimeMillis: 300000
    # 申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
    testWhileIdle: true
    # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
    testOnBorrow: false
    # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
    testOnReturn: false
    # 检查连接是否有效的SQL
    validationQuery: SELECT 1 FROM DUAL
    # 是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
    poolPreparedStatements: true
    # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。
    maxOpenPreparedStatements: 20
    # 1.1.4中新增加的配置，如果有initialSize数量较多时，打开会加快应用启动时间
    asyncInit: true
    #=============================
    #以上是DruidDataSource通用配置